name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  checkVersion:
    runs-on: ubuntu-latest
    outputs:
      newVersion: ${{ steps.newVersion.outputs.newVersion }}
    steps:
      - uses: actions/checkout@v4
      - id: newVersion
        run: >-
            echo "newVersion=$([ "$(npm view @bad-software/eslint-config version)" != "$(cat package.json | jq -r '.version')" ] && echo 'true' || echo 'false' )" >> "$GITHUB_OUTPUT"

  publish:
    runs-on: ubuntu-latest
    needs: checkVersion
    if: needs.checkVersion.outputs.newVersion == 'true'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
#          registry-url: https://npm.pkg.github.com
          registry-url: https://registry.npmjs.org
          scope: '@bad-software'
      - run: yarn --frozen-lockfile
      - run: npm publish --access public
        env:
#          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
