name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
#          registry-url: https://npm.pkg.github.com
          registry-url: https://registry.npmjs.org
          scope: '@bad-software'
      - run: yarn --frozen-lockfile
      - run: npm publish
        env:
#          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
